### ISSUE TITLE
你好，我有2个问题

### ISSUE THREAD

**Issue by BadDeveloper2022** [vanjoge/RTVS#3]
【1】支持加密传输吗？
【2】宽带的上下行计算过吗？ 比如 1080P  200个并发

**Comment by vanjoge** [comment]
1.RTVS支持的是JT1078协议，1078未有定义加密，所以并不支持；
2.带宽问题你根据自己的场景算，带宽除了与分辨率外还与帧率有关，车载行业1080P大都不是25或30帧，大部分都只有15或10帧以下，所以算带宽要根据你的实际设备来估算。一般是单路带宽平均值*并发路数计算。
